version: "3"
services:
  app:
    image: ghcr.io/trim21/cactbot_importer:latest
    networks:
      - cactbot_importer
    ports:
      - "5008:3002"
    environment:
      TZ: "Asia/Shanghai"

networks:
  cactbot_importer:
