package fetch

import (
	"bytes"
	"fmt"
	"net/url"
	"strings"

	"github.com/pkg/errors"

	"cactbot_importer/pkg/http"
	"cactbot_importer/pkg/repo"
	"cactbot_importer/pkg/wrap"
)

func Fetch(urls []string) (string, error) {
	w := bytes.NewBuffer(nil)
	ref := make(map[string]string)
	added := make(map[string]struct{})
	processedUrls := make([]string, 0, len(urls))

	w.WriteString("// generated by https://cactbot-importer.trim21.cn/\n")
	w.WriteString("// included files:\n//\n")

	add := func(url, msg string) bool {
		if _, ok := added[url]; ok {
			w.WriteString(msg + url + " [skipped]\n")
			return false
		} else {
			w.WriteString(msg + url + "\n")
			added[url] = struct{}{}
			processedUrls = append(processedUrls, url)
			return true
		}
	}

	for _, u := range urls {
		u = strings.TrimSpace(u)
		if strings.HasSuffix(u, ".json") {
			w.WriteString("// " + u + "\n")

			urls, err := repo.Fetch(u)
			if err != nil {
				if errors.Is(err, repo.ErrNestedRepo) {
					return "", wrap.Rewrite(err, fmt.Sprintf("不能嵌套repo %s", u))
				}
				return "", err
			}

			for _, ur := range urls {
				if add(ur, "//   ") {
					ref[ur] = u
				}
			}
			w.WriteString("//\n")
		} else {
			add(u, "// ")
		}
	}

	w.WriteString("\n")

	err := joinURLs(w, processedUrls, ref)

	return w.String(), err
}

func joinURLs(w *bytes.Buffer, urls []string, ref map[string]string) error {
	for _, u := range urls {
		ur, err := url.Parse(u)
		if err != nil {
			return errors.Wrapf(err, "不是合法的HTTP链接 %s", u)
		}
		ur.RawQuery = ""
		striped := &url.URL{
			Scheme: ur.Scheme,
			Host:   ur.Host,
			Path:   ur.Path,
		}

		resp, err := http.Get(striped)
		if resp.StatusCode() >= 300 {
			if v, found := ref[u]; found {
				return fmt.Errorf("无法获取合集 %s\n\n文件 %s 消失", v, u)
			}
			return fmt.Errorf("无法获取文件 %s", u)
		}

		t, err := process(resp)
		if err != nil {
			if errors.Is(err, ErrTransform) {
				return wrap.Rewrite(err, t)
			}
			return err
		}
		w.WriteString("// start " + striped.String() + "\n")
		w.WriteString("console.log('cactbot importer: [INFO] executing script from " + striped.String() + "');\n")
		w.WriteString(t)
		w.WriteString("// end " + striped.String() + "\n\n")
	}

	return nil
}
