name: build

on:
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - run: go get ./...

      - run: go build -ldflags '-w -s' -trimpath -o dist/app
        env:
          CGO_ENABLED: 0

      - run: docker build -t ghcr.io/trim21/cactbot-importer:latest .
