name: docker

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - run: |
          go get ./...
          go install github.com/markbates/pkger/cmd/pkger

      - run: go generate ./...

      - run: go build -o dist/app
        env:
          CGO_ENABLED: 0

      - run: docker build -t ghcr.io/trim21/cactbot_importer:latest .

      - run: |
          echo $DOCKER_TOKEN | docker login ghcr.io -u Trim21 --password-stdin
          docker push ghcr.io/trim21/cactbot_importer:latest
        env:
          DOCKER_TOKEN: ${{ github.token }}
