name: docker

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - run: go get ./...

      - run: go build -ldflags '-w -s' -trimpath -o dist/app
        env:
          CGO_ENABLED: 0

      - run: docker build -t ghcr.io/trim21/cactbot-importer:latest .

      - run: |
          echo $DOCKER_TOKEN | docker login ghcr.io -u Trim21 --password-stdin
          docker push ghcr.io/trim21/cactbot-importer:latest
        env:
          DOCKER_TOKEN: ${{ github.token }}
